services:
  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=horizon_user
      - POSTGRES_PASSWORD=horizon_password
      - POSTGRES_DB=horizon_fms
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U horizon_user -d horizon_fms" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  seq:
    image: datalust/seq:2024.3
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "${SEQ_PORT:-5341}:80"
    volumes:
      - seq-data:/data
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  api-service:
    build:
      context: .
      dockerfile: FileManagementSystem.API/Dockerfile
    ports:
      - "${API_PORT:-5295}:5295"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - ./storage:/app/storage
      - api-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Storage__RootPath=/app/storage
      - ThumbnailSettings__Directory=/app/storage/thumbnails
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=horizon_fms;Username=horizon_user;Password=horizon_password;
      - ConnectionStrings__Redis=redis:6379
      - Serilog__SeqServerUrl=http://seq:80
      - CloudinarySettings__CloudName=${CLOUDINARY_CLOUD_NAME}
      - CloudinarySettings__ApiKey=${CLOUDINARY_API_KEY}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}
      - CloudinarySettings__IsEnabled=true
    restart: always

  web-service:
    build:
      context: ./FileManagementSystem.Web
      dockerfile: Dockerfile
    ports:
      - "${WEB_PORT:-8080}:80"
    depends_on:
      api-service:
        condition: service_started
    restart: always

volumes:
  postgres-data:
  api-data:
  seq-data:
  redis-data:
